package com.example.piloto.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import org.springframework.data.annotation.Id;
//import org.springframework.data.mongodb.core.mapping.Document;

import java.util.Date;
import java.util.List;
import java.util.Map;

@Data
@DynamoDBTable(tableName = "piloto")
//@Document(collection = "estrategia")
public class Estrategia {

//    @Id
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String nome;

    @DynamoDBAttribute
    private String descricao;

    @DynamoDBAttribute
    private Date dataCriacao;

    @DynamoDBAttribute
    private List<Map<String, String>> whitelist;

    @DynamoDBAttribute
    private List<Map<String, String>> blacklist;

}
